# Funding options for Compressy
# Support the development of Compressy!

# GitHub Sponsors
# github: [username]

# Patreon
# patreon: username

# Ko-fi
# ko_fi: username

# Custom links
custom: ["https://www.twitch.tv/strixun", "https://sponsor.idling.app"]

